# Generated by Django 3.2.5 on 2021-07-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_sell_date', models.DateField()),
                ('bid_sell', models.CharField(max_length=20)),
                ('bitcoin_amount', models.FloatField()),
                ('actual_amount', models.FloatField()),
            ],
        ),
    ]
